### ISSUE TITLE
Purpose of 1.3 multiplier in checking covalent bonds

### ISSUE THREAD

**Issue by ljmartin** [jensengroup/xyz2mol#15]
Thanks for the great script.

Would someone please explain the purpose of the GetRCovalent covalent radius being multiplied by 1.3?
ie:
https://github.com/jensengroup/xyz2mol/blob/2b9f96836dde5c983bd6dd7266c1f422e8bbb436/xyz2mol.py#L392
thanks

**Comment by cstein** [comment]
Hi Martin,

When you want to test of there is a covalent bond between to pairs of atoms you use the covalent radii and check if the distance between the pair of atoms is shorter. It turns out that using only the covalent radii (from `GetRCovalent`) will not find bonds that are *slightly longer* then their equilibrium distance. So you add this fudge factor of 1.3 to make sure you also get those.

**Comment by ljmartin** [comment]
Great, thanks!
